FROM node:22-bookworm-slim AS dependencies
WORKDIR /app
COPY package.json package-lock.json ./
RUN npm ci

FROM dependencies AS portal-build
COPY portal-web ./portal-web
RUN npm run build:portal

FROM dependencies AS admin-build
COPY admin-web ./admin-web
RUN npm run build:admin-web

FROM node:22-bookworm-slim AS portal-runtime
ENV NODE_ENV=production
ARG PORT=3100
ENV PORT=$PORT
WORKDIR /app
COPY --from=portal-build /app/dist/portal-web ./dist
COPY frontend-server.mjs ./frontend-server.mjs
EXPOSE $PORT
CMD ["node", "frontend-server.mjs"]

FROM node:22-bookworm-slim AS admin-runtime
ENV NODE_ENV=production
ARG PORT=3200
ENV PORT=$PORT
WORKDIR /app
COPY --from=admin-build /app/dist/admin-web ./dist
COPY frontend-server.mjs ./frontend-server.mjs
EXPOSE $PORT
CMD ["node", "frontend-server.mjs"]
