import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
const root=fileURLToPath(new URL("../",import.meta.url));
const messages=JSON.parse(fs.readFileSync(path.join(root,"clients/locales/messages.json"),"utf8"));
const entries=Object.entries(messages).sort(([a],[b])=>a.localeCompare(b));
const placeholders=value=>[...value.matchAll(/\{(\d+)\}/g)].map(m=>m[1]).sort().join(",");
for(const [key,values] of entries) {
  if(!/^[a-z][a-z0-9_]*$/.test(key))throw Error(`Invalid resource key: ${key}`);
  for(const locale of ["en","zh","ru"]) {
    if(!values[locale]?.trim())throw Error(`Missing ${locale}: ${key}`);
    if(placeholders(values[locale])!==placeholders(values.en))throw Error(`Placeholder mismatch: ${locale}/${key}`);
  }
}
function write(relative,text){const file=path.join(root,relative);if(process.argv.includes("--check")){if(!fs.existsSync(file)||fs.readFileSync(file,"utf8")!==text)throw Error(`Outdated generated resource: ${relative}`);}else{fs.mkdirSync(path.dirname(file),{recursive:true});fs.writeFileSync(file,text);}}
const xml=value=>value.replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;");
for(const [locale,folder] of [["en","values"],["zh","values-zh"],["ru","values-ru"]]) {
  const body=entries.map(([key,v])=>`  <string name="${key}">${xml(v[locale].replaceAll("%","%%").replace(/\{(\d+)\}/g,(_,n)=>`%${Number(n)+1}$s`).replaceAll("\\","\\\\").replaceAll("\n","\\n").replaceAll("'","\\'").replaceAll('"','\\"'))}</string>`).join("\n");
  write(`clients/android/app/src/main/res/${folder}/strings.xml`,`<?xml version="1.0" encoding="utf-8"?>\n<!-- Generated by scripts/native-locales.mjs. -->\n<resources>\n${body}\n</resources>\n`);
}
const strings=Object.fromEntries(entries.map(([key,v])=>[key,{extractionState:"manual",localizations:Object.fromEntries([["en","en"],["zh","zh-Hans"],["ru","ru"]].map(([source,locale])=>[locale,{stringUnit:{state:"translated",value:v[source].replaceAll("%","%%").replace(/\{(\d+)\}/g,(_,n)=>`%${Number(n)+1}$@`)}}]))}]));
write("clients/apple/Shared/Native.xcstrings",JSON.stringify({sourceLanguage:"en",strings,version:"1.0"},null,2)+"\n");
for(const [locale,suffix] of [["en",""],["zh",".zh"],["ru",".ru"]]) {
  write(`clients/windows/Veilbird/Resources/Native${suffix}.resx`,`<?xml version="1.0" encoding="utf-8"?>\n<!-- Generated by scripts/native-locales.mjs. -->\n<root>\n  <resheader name="resmimetype"><value>text/microsoft-resx</value></resheader>\n  <resheader name="version"><value>2.0</value></resheader>\n${entries.map(([key,v])=>`  <data name="${key}" xml:space="preserve"><value>${xml(v[locale])}</value></data>`).join("\n")}\n</root>\n`);
}
console.log(`Native resources: ${entries.length} messages × 3 locales verified.`);
